
# the root directory for the poject examples
PRJ_ROOT       = /Users/rhalstea/projects/vhdl_api/src
EXAMPLE_ROOT   = /Users/rhalstea/projects/vhdl_api/examples

# important directores
INCLUDE_DIR = $(PRJ_ROOT)/include
OBJECT_DIR  = $(PRJ_ROOT)/bin/lib

vpath %.o $(OBJECT_DIR)

# setup the compiler options
CXX         = g++
CXX_FLAGS   = -I$(INCLUDE_DIR) -L$(OBJECT_DIR)
CC          = gcc


