
# the root directory for the project
PRJ_ROOT = /Users/rhalstea/projects/vhdl_api/src

# the compiler to use
CXX = g++
CC = gcc

CXX_FLAGS = -fPIC

# important directories
INCLUDE_DIR    = $(PRJ_ROOT)/include
LIBRARY_DIR    = $(PRJ_ROOT)/lib
OBJECT_DIR     = $(PRJ_ROOT)/bin/lib

# sub directories for include files
INCLUDE_SUB_DIR   = /vhdl

# paths to required programs
ECHO        := /bin/echo 
