
# the root directory for the project
PRJ_ROOT = /Users/rhalstea/projects/vhdl_api/src

# the compiler to use
CXX               = g++
CC                = gcc

CXX_FLAGS         = -Wall -fPIC


# compiler flags to generate shared libraries
SHARED_LIB_FLAGS  = @echo "Unsupported OS"
OS_TYPE           = $(shell uname)

ifeq ($(OS_TYPE), Linux)
   SHARED_LIB_FLAGS = ld -G
endif

ifeq ($(OS_TYPE), Darwin) # Mac OSX
   SHARED_LIB_FLAGS = -dynamiclib -undefined suppress -flat_namespace
endif

# important directories
INCLUDE_DIR       = $(PRJ_ROOT)/include
LIBRARY_DIR       = $(PRJ_ROOT)/lib
OBJECT_DIR        = $(PRJ_ROOT)/bin/lib

# sub directories for include files
INCLUDE_SUB_DIR   = vhdl

# paths to required programs
ECHO              := /bin/echo 
